Added step for auto-download and unzip of VST3 SDK to CMakeLists.txt.
logicomacorp/WaveSabre pull request #92
Opened 2022-01-05 11:45 UTC by LeStahL

This will check at configure time if the VST3 SDK is present, and if not: download & unpack it into the correct folder.

2022-01-05 17:24 UTC, kusma commented on CMakeLists.txt
> +endif()
I'm skeptical of build systems that downloads and compiles code behind my back, without giving me a reasonable chance to intervene. IMO, auto-downloading should be an opt-in feature.

2022-01-05 17:49 UTC, LeStahL commented on CMakeLists.txt
> +endif()
Adjusted accordingly.

2022-01-07 23:04 UTC, yupferris requested changes
Cheers for this! Only one minor change, and I'll be happy to accept it :)

2022-01-07 23:04 UTC, yupferris commented on CMakeLists.txt
> +set(DOWNLOAD_DEPENDENCIES CACHE BOOL OFF)
I'd like this to be called `DOWNLOAD_VST3SDK`.

2022-01-07 23:11 UTC, LeStahL commented on CMakeLists.txt
> +set(DOWNLOAD_DEPENDENCIES CACHE BOOL OFF)
Done.

2022-01-08 06:23 UTC, yupferris approved these changes
cheers!

2022-01-08 06:24 UTC, merged